import { test, expect } from '@playwright/test'

test('Admin signs in and completes the governance onboarding journey', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Local E2E Admin')).toBeVisible()
  await expect(page.getByText('administrator')).toBeVisible()
  await page.getByRole('button', { name: 'Agents' }).click()
  await page.getByTestId('runtime-name').fill('journey-agent')
  await page.getByTestId('runtime-endpoint').fill('https://agent.example.test')
  await page.getByTestId('runtime-submit').click()
  await expect(page.getByTestId('identity-action-result')).toContainText('registered.')
  await expect(page.getByTestId('runtime-agents')).toBeVisible()
  await page.getByRole('button', { name: 'Tools & MCP' }).click()
  await page.getByTestId('install-mcp-btn').click()
  await page.getByTestId('wiz-name').fill('journey-mcp')
  await page.getByTestId('wiz-url').fill('https://mcp.example.test/sse')
  await page.getByText('Next →').click()
  await page.getByTestId('wiz-install-btn').click()
  await expect(page.getByTestId('wiz-installed-ok')).toBeVisible({ timeout: 10000 })
  await page.getByTestId('wiz-next-2').click()
  await page.getByTestId('wiz-agents').fill('agt_e2e_001')
  await page.getByTestId('wiz-authorize-btn').click()
  await expect(page.getByTestId('wiz-done')).toBeVisible({ timeout: 10000 })
  await page.getByTestId('wiz-finish').click()
  await expect(page.getByTestId('mcp-table')).toContainText('journey-mcp')
  const mcpRow = page.getByTestId('mcp-table').locator('tr', { hasText: 'journey-mcp' }).first()
  await mcpRow.getByRole('button', { name: 'Who has it?' }).click()
  await expect(page.getByTestId('access-list')).toContainText('agt_e2e_001')
  const policyName = `journey-policy-${Date.now().toString(36)}`
  const response = await page.request.post('/api/bff/policies', {
    data: { name: policyName, engine: 'yaml', definition: '- name: allow-github\n  actions: ["call"]\n  resources: ["mcp/*"]\n  decision: allow' },
  })
  expect(response.status()).toBe(201)
  await page.getByRole('button', { name: 'Access' }).click()
  await expect(page.getByText(policyName)).toBeVisible({ timeout: 10000 })
  await page.getByTestId('simulate-action').fill('call')
  await page.getByTestId('simulate-resource').fill('mcp/github')
  await page.getByTestId('simulate-yaml').fill('- name: allow-call\n  actions: ["call"]\n  resources: ["mcp/*"]\n  decision: allow')
  await page.getByTestId('simulate-run').click()
  await expect(page.getByTestId('simulation-result')).toContainText('"decision": "allow"')
  await page.getByRole('button', { name: 'Security' }).click()
  await expect(page.getByTestId('audit-integrity')).toContainText('intact')
})
